### ISSUE TITLE
Call for feedback on TPAC 2022 logistics survey for WebView CG meeting

### ISSUE THREAD

**Issue by QingAn** [WebView-CG/usage-and-challenges#13]
Hi all,

This year's TPAC (12-16 September 2022) will be a hybrid format, with onsite in Vancouver, Canada. W3C CG will have the opportunity to hold a 2-hour meeting.

W3C team is collecting the info from each CG about the logistics, and the deadline is **31 May**

To fill in the survey, I'd like to call for feedback on the following questions:

1. Do you plan to attend this year's TPAC in F2F?
2. Day preference: there are four options (Mon 12 Sep, Tue 13 Sep, Thu 15 Sep, Fri 16 Sep)
3. Slot preference: there are four options (8:30-10:30 PST, 10:30-12:30 PST, 13:30-15:30 PST, 15:30-17:30 PST)

Please indicate your preference and any other comment. 
Early response is highly encouraged.

**Comment by QingAn** [comment]
1. Cannot attend F2F
2. No preference, but need to avoid the conflict with MiniApp WG meeting,  ePub WG meeting .
3. 8:30-10:30 PST

**Comment by rayankans** [comment]
1. Attending F2F
2. no preference
3. no preference

**Comment by Token-LiMing** [comment]
1. Cannot attend F2F
2. No preference
3. 8:30-10:30 PST

**Comment by tomayac** [comment]
1. Attending F2F
2. no preference
3. no preference

**Comment by espinr** [comment]
1. Attending F2F
2. no preference
3. no preference

**Comment by chrisn** [comment]
1. Likely to attend F2F
2. Monday or Tuesday (prefer to avoid overlap with media related groups)
3. No preference
