### ISSUE TITLE
TPAC agenda

### ISSUE THREAD

**Issue by rayankans** [WebView-CG/usage-and-challenges#35]
I'm proposing a tentative agenda for the CG TPAC meet-up. Feel free to add items to the agenda in this issue.

- Introduction to the WebView CG (15 min)
- Introduction on CG report "WebView: Usage Scenarios and Challenges" + Q&A (45 min)
- Discussion of open GitHub issues (15-30 min)
- Discussion of next steps for the CG (30-45 min)
  - Collect more use cases?
  - Incubate technical proposals?

**Comment by muodov** [comment]
@QingAn @rayankans are there plans to meet up at TPAC 2023? I am planning to visit in person this time.
